// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpcapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ScreenshotsClient is the client API for Screenshots service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScreenshotsClient interface {
	Upload(ctx context.Context, in *Screenshot, opts ...grpc.CallOption) (*ScreenshotLink, error)
}

type screenshotsClient struct {
	cc grpc.ClientConnInterface
}

func NewScreenshotsClient(cc grpc.ClientConnInterface) ScreenshotsClient {
	return &screenshotsClient{cc}
}

func (c *screenshotsClient) Upload(ctx context.Context, in *Screenshot, opts ...grpc.CallOption) (*ScreenshotLink, error) {
	out := new(ScreenshotLink)
	err := c.cc.Invoke(ctx, "/foxyshot.Screenshots/upload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScreenshotsServer is the server API for Screenshots service.
// All implementations must embed UnimplementedScreenshotsServer
// for forward compatibility
type ScreenshotsServer interface {
	Upload(context.Context, *Screenshot) (*ScreenshotLink, error)
	mustEmbedUnimplementedScreenshotsServer()
}

// UnimplementedScreenshotsServer must be embedded to have forward compatible implementations.
type UnimplementedScreenshotsServer struct {
}

func (UnimplementedScreenshotsServer) Upload(context.Context, *Screenshot) (*ScreenshotLink, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedScreenshotsServer) mustEmbedUnimplementedScreenshotsServer() {}

// UnsafeScreenshotsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScreenshotsServer will
// result in compilation errors.
type UnsafeScreenshotsServer interface {
	mustEmbedUnimplementedScreenshotsServer()
}

func RegisterScreenshotsServer(s grpc.ServiceRegistrar, srv ScreenshotsServer) {
	s.RegisterService(&Screenshots_ServiceDesc, srv)
}

func _Screenshots_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Screenshot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScreenshotsServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/foxyshot.Screenshots/upload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScreenshotsServer).Upload(ctx, req.(*Screenshot))
	}
	return interceptor(ctx, in, info, handler)
}

// Screenshots_ServiceDesc is the grpc.ServiceDesc for Screenshots service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Screenshots_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "foxyshot.Screenshots",
	HandlerType: (*ScreenshotsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "upload",
			Handler:    _Screenshots_Upload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "foxyshot.proto",
}
