// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: foxyshot.proto

package grpcapi

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Screenshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image     []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Extension string `protobuf:"bytes,2,opt,name=extension,proto3" json:"extension,omitempty"`
}

func (x *Screenshot) Reset() {
	*x = Screenshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foxyshot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Screenshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Screenshot) ProtoMessage() {}

func (x *Screenshot) ProtoReflect() protoreflect.Message {
	mi := &file_foxyshot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Screenshot.ProtoReflect.Descriptor instead.
func (*Screenshot) Descriptor() ([]byte, []int) {
	return file_foxyshot_proto_rawDescGZIP(), []int{0}
}

func (x *Screenshot) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Screenshot) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

type ScreenshotLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *ScreenshotLink) Reset() {
	*x = ScreenshotLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foxyshot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScreenshotLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotLink) ProtoMessage() {}

func (x *ScreenshotLink) ProtoReflect() protoreflect.Message {
	mi := &file_foxyshot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotLink.ProtoReflect.Descriptor instead.
func (*ScreenshotLink) Descriptor() ([]byte, []int) {
	return file_foxyshot_proto_rawDescGZIP(), []int{1}
}

func (x *ScreenshotLink) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

var File_foxyshot_proto protoreflect.FileDescriptor

var file_foxyshot_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x66, 0x6f, 0x78, 0x79, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x66, 0x6f, 0x78, 0x79, 0x73, 0x68, 0x6f, 0x74, 0x22, 0x40, 0x0a, 0x0a, 0x53, 0x63,
	0x72, 0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x24, 0x0a, 0x0e,
	0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69,
	0x6e, 0x6b, 0x32, 0x47, 0x0a, 0x0b, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74,
	0x73, 0x12, 0x38, 0x0a, 0x06, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x14, 0x2e, 0x66, 0x6f,
	0x78, 0x79, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f,
	0x74, 0x1a, 0x18, 0x2e, 0x66, 0x6f, 0x78, 0x79, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x53, 0x63, 0x72,
	0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x42, 0x0b, 0x5a, 0x09, 0x2e,
	0x3b, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_foxyshot_proto_rawDescOnce sync.Once
	file_foxyshot_proto_rawDescData = file_foxyshot_proto_rawDesc
)

func file_foxyshot_proto_rawDescGZIP() []byte {
	file_foxyshot_proto_rawDescOnce.Do(func() {
		file_foxyshot_proto_rawDescData = protoimpl.X.CompressGZIP(file_foxyshot_proto_rawDescData)
	})
	return file_foxyshot_proto_rawDescData
}

var file_foxyshot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_foxyshot_proto_goTypes = []interface{}{
	(*Screenshot)(nil),     // 0: foxyshot.Screenshot
	(*ScreenshotLink)(nil), // 1: foxyshot.ScreenshotLink
}
var file_foxyshot_proto_depIdxs = []int32{
	0, // 0: foxyshot.Screenshots.upload:input_type -> foxyshot.Screenshot
	1, // 1: foxyshot.Screenshots.upload:output_type -> foxyshot.ScreenshotLink
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_foxyshot_proto_init() }
func file_foxyshot_proto_init() {
	if File_foxyshot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_foxyshot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Screenshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foxyshot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScreenshotLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_foxyshot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_foxyshot_proto_goTypes,
		DependencyIndexes: file_foxyshot_proto_depIdxs,
		MessageInfos:      file_foxyshot_proto_msgTypes,
	}.Build()
	File_foxyshot_proto = out.File
	file_foxyshot_proto_rawDesc = nil
	file_foxyshot_proto_goTypes = nil
	file_foxyshot_proto_depIdxs = nil
}
